name 'eas-lemp'
maintainer 'opscale'
maintainer_email 'cookbooks@opscale.com'
license 'Apache 2.0'
description 'Installs/Configures eas-lemp'
long_description 'Installs/Configures eas-lemp'
version '0.1.1'

depends 'eas-base'
depends 'nginx'
depends 'mysql'
depends 'php'
depends 'php-fpm'
